package com.jme3.input;

import android.icu.text.DateFormat;
import android.media.audiofx.AudioEffect;
import androidx.exifinterface.media.ExifInterface;
import b3.s;
import java.lang.constant.ConstantDescs;
import org.eclipse.jdt.core.Signature;
import org.openjdk.tools.doclint.DocLint;
import yd.C16181m;

public class KeyNames {
    private static final String[] KEY_NAMES;

    static {
        String[] strArr = new String[255];
        KEY_NAMES = strArr;
        strArr[0] = "Unknown";
        strArr[11] = "0";
        strArr[2] = "1";
        strArr[3] = "2";
        strArr[4] = "3";
        strArr[5] = "4";
        strArr[6] = "5";
        strArr[7] = "6";
        strArr[8] = "7";
        strArr[9] = "8";
        strArr[10] = "9";
        strArr[16] = "Q";
        strArr[17] = ExifInterface.LONGITUDE_WEST;
        strArr[18] = "E";
        strArr[19] = "R";
        strArr[20] = ExifInterface.GPS_DIRECTION_TRUE;
        strArr[21] = "Y";
        strArr[22] = "U";
        strArr[23] = Signature.SIG_INT;
        strArr[24] = "O";
        strArr[25] = "P";
        strArr[30] = ExifInterface.GPS_MEASUREMENT_IN_PROGRESS;
        strArr[31] = "S";
        strArr[32] = Signature.SIG_DOUBLE;
        strArr[33] = Signature.SIG_FLOAT;
        strArr[34] = "G";
        strArr[35] = DateFormat.HOUR24;
        strArr[36] = Signature.SIG_LONG;
        strArr[37] = "K";
        strArr[38] = "L";
        strArr[44] = Signature.SIG_BOOLEAN;
        strArr[45] = "X";
        strArr[46] = Signature.SIG_CHAR;
        strArr[47] = "V";
        strArr[48] = Signature.SIG_BYTE;
        strArr[49] = "N";
        strArr[50] = "M";
        strArr[59] = "F1";
        strArr[60] = "F2";
        strArr[61] = "F3";
        strArr[62] = "F4";
        strArr[63] = "F5";
        strArr[64] = "F6";
        strArr[65] = "F7";
        strArr[66] = "F8";
        strArr[67] = "F9";
        strArr[68] = "F10";
        strArr[87] = "F11";
        strArr[88] = "F12";
        strArr[100] = "F13";
        strArr[101] = "F14";
        strArr[102] = "F15";
        strArr[82] = "Numpad 0";
        strArr[79] = "Numpad 1";
        strArr[80] = "Numpad 2";
        strArr[81] = "Numpad 3";
        strArr[75] = "Numpad 4";
        strArr[76] = "Numpad 5";
        strArr[77] = "Numpad 6";
        strArr[71] = "Numpad 7";
        strArr[72] = "Numpad 8";
        strArr[73] = "Numpad 9";
        strArr[141] = "Numpad =";
        strArr[156] = "Numpad Enter";
        strArr[179] = "Numpad ,";
        strArr[181] = "Numpad /";
        strArr[74] = "Numpad -";
        strArr[83] = "Numpad .";
        strArr[56] = "Left Alt";
        strArr[184] = "Right Alt";
        strArr[29] = "Left Ctrl";
        strArr[157] = "Right Ctrl";
        strArr[42] = "Left Shift";
        strArr[54] = "Right Shift";
        strArr[219] = "Left Option";
        strArr[220] = "Right Option";
        strArr[12] = "-";
        strArr[13] = "=";
        strArr[26] = "[";
        strArr[27] = "]";
        strArr[39] = ";";
        strArr[40] = "'";
        strArr[41] = "`";
        strArr[43] = C16181m.f130232i;
        strArr[51] = DocLint.SEPARATOR;
        strArr[52] = ".";
        strArr[53] = "/";
        strArr[55] = "*";
        strArr[78] = "+";
        strArr[146] = s.f32937c;
        strArr[147] = ConstantDescs.DEFAULT_NAME;
        strArr[145] = "@";
        strArr[221] = "Apps";
        strArr[222] = "Power";
        strArr[223] = "Sleep";
        strArr[149] = "Stop";
        strArr[1] = "Esc";
        strArr[28] = "Enter";
        strArr[57] = "Space";
        strArr[14] = "Backspace";
        strArr[15] = "Tab";
        strArr[183] = "SysRq";
        strArr[197] = "Pause";
        strArr[199] = "Home";
        strArr[201] = "Page Up";
        strArr[209] = "Page Down";
        strArr[207] = "End";
        strArr[210] = AudioEffect.EFFECT_INSERT;
        strArr[211] = "Delete";
        strArr[200] = "Up";
        strArr[203] = "Left";
        strArr[205] = "Right";
        strArr[208] = "Down";
        strArr[69] = "Num Lock";
        strArr[58] = "Caps Lock";
        strArr[70] = "Scroll Lock";
        strArr[112] = "Kana";
        strArr[121] = "Convert";
        strArr[123] = "No Convert";
        strArr[125] = "Yen";
        strArr[144] = "Circumflex";
        strArr[148] = "Kanji";
        strArr[150] = "Ax";
        strArr[151] = "Unlabeled";
    }

    public static String getName(int i10) {
        return KEY_NAMES[i10];
    }
}
