package org.eclipse.jdt.internal.compiler.parser;

import com.google.firebase.analytics.FirebaseAnalytics;
import org.eclipse.jdt.core.compiler.CharOperation;

public interface JavadocTagConstants {
    public static final int ALL_TAGS_LENGTH;
    public static final int BLOCK_IDX = 0;
    public static final char[][][] BLOCK_TAGS;
    public static final int BLOCK_TAGS_LENGTH;
    public static final char[][] CLASS_TAGS;
    public static final char[][] COMPILATION_UNIT_TAGS;
    public static final char[][] FIELD_TAGS;
    public static final char[] HREF_TAG;
    public static final int INLINE_IDX = 1;
    public static final char[][][] INLINE_TAGS;
    public static final int INLINE_TAGS_LENGTH;
    public static final short[] JAVADOC_TAG_TYPE;
    public static final char[][] METHOD_TAGS;
    public static final char[][] MODULE_TAGS;
    public static final int NO_TAG_VALUE = 0;
    public static final int ORDERED_TAGS_NUMBER = 3;
    public static final char[][] PACKAGE_TAGS;
    public static final int PARAM_TAG_EXPECTED_ORDER = 0;
    public static final int SEE_TAG_EXPECTED_ORDER = 2;
    public static final char[] TAG_API_NOTE;
    public static final int TAG_API_NOTE_LENGTH;
    public static final int TAG_API_NOTE_VALUE = 27;
    public static final char[] TAG_AUTHOR;
    public static final int TAG_AUTHOR_LENGTH;
    public static final int TAG_AUTHOR_VALUE = 12;
    public static final char[] TAG_CATEGORY;
    public static final int TAG_CATEGORY_LENGTH;
    public static final int TAG_CATEGORY_VALUE = 11;
    public static final char[] TAG_CODE;
    public static final int TAG_CODE_LENGTH;
    public static final int TAG_CODE_VALUE = 18;
    public static final char[] TAG_DEPRECATED;
    public static final int TAG_DEPRECATED_LENGTH;
    public static final int TAG_DEPRECATED_VALUE = 1;
    public static final char[] TAG_DOC_ROOT;
    public static final int TAG_DOC_ROOT_LENGTH;
    public static final int TAG_DOC_ROOT_VALUE = 20;
    public static final char[] TAG_EXCEPTION;
    public static final int TAG_EXCEPTION_LENGTH;
    public static final int TAG_EXCEPTION_VALUE = 5;
    public static final char[] TAG_HIDDEN;
    public static final int TAG_HIDDEN_LENGTH;
    public static final int TAG_HIDDEN_VALUE = 24;
    public static final char[] TAG_IMPL_NOTE;
    public static final int TAG_IMPL_NOTE_LENGTH;
    public static final int TAG_IMPL_NOTE_VALUE = 29;
    public static final char[] TAG_IMPL_SPEC;
    public static final int TAG_IMPL_SPEC_LENGTH;
    public static final int TAG_IMPL_SPEC_VALUE = 28;
    public static final char[] TAG_INDEX;
    public static final int TAG_INDEX_LENGTH;
    public static final int TAG_INDEX_VALUE = 25;
    public static final char[] TAG_INHERITDOC;
    public static final int TAG_INHERITDOC_LENGTH;
    public static final int TAG_INHERITDOC_VALUE = 9;
    public static final char[] TAG_LINK;
    public static final char[] TAG_LINKPLAIN;
    public static final int TAG_LINKPLAIN_LENGTH;
    public static final int TAG_LINKPLAIN_VALUE = 8;
    public static final int TAG_LINK_LENGTH;
    public static final int TAG_LINK_VALUE = 7;
    public static final char[] TAG_LITERAL;
    public static final int TAG_LITERAL_LENGTH;
    public static final int TAG_LITERAL_VALUE = 19;
    public static final char[][] TAG_NAMES;
    public static final int TAG_OTHERS_VALUE = 100;
    public static final char[] TAG_PARAM;
    public static final int TAG_PARAM_LENGTH;
    public static final int TAG_PARAM_VALUE = 2;
    public static final char[] TAG_PROVIDES;
    public static final int TAG_PROVIDES_LENGTH;
    public static final int TAG_PROVIDES_VALUE = 23;
    public static final char[] TAG_RETURN;
    public static final int TAG_RETURN_LENGTH;
    public static final int TAG_RETURN_VALUE = 3;
    public static final char[] TAG_SEE;
    public static final int TAG_SEE_LENGTH;
    public static final int TAG_SEE_VALUE = 6;
    public static final char[] TAG_SERIAL;
    public static final char[] TAG_SERIAL_DATA;
    public static final int TAG_SERIAL_DATA_LENGTH;
    public static final int TAG_SERIAL_DATA_VALUE = 14;
    public static final char[] TAG_SERIAL_FIELD;
    public static final int TAG_SERIAL_FIELD_LENGTH;
    public static final int TAG_SERIAL_FIELD_VALUE = 15;
    public static final int TAG_SERIAL_LENGTH;
    public static final int TAG_SERIAL_VALUE = 13;
    public static final char[] TAG_SINCE;
    public static final int TAG_SINCE_LENGTH;
    public static final int TAG_SINCE_VALUE = 16;
    public static final char[] TAG_SUMMARY;
    public static final int TAG_SUMMARY_LENGTH;
    public static final int TAG_SUMMARY_VALUE = 26;
    public static final char[] TAG_SYSTEM_PROPERTY;
    public static final int TAG_SYSTEM_PROPERTY_LENGTH;
    public static final int TAG_SYSTEM_PROPERTY_VALUE = 21;
    public static final char[] TAG_THROWS;
    public static final int TAG_THROWS_LENGTH;
    public static final int TAG_THROWS_VALUE = 4;
    public static final short TAG_TYPE_BLOCK = 2;
    public static final short TAG_TYPE_INLINE = 1;
    public static final short TAG_TYPE_NONE = 0;
    public static final char[] TAG_USES;
    public static final int TAG_USES_LENGTH;
    public static final int TAG_USES_VALUE = 22;
    public static final char[] TAG_VALUE;
    public static final int TAG_VALUE_LENGTH;
    public static final int TAG_VALUE_VALUE = 10;
    public static final char[] TAG_VERSION;
    public static final int TAG_VERSION_LENGTH;
    public static final int TAG_VERSION_VALUE = 17;
    public static final int THROWS_TAG_EXPECTED_ORDER = 1;

    static {
        char[] charArray = "deprecated".toCharArray();
        TAG_DEPRECATED = charArray;
        char[] charArray2 = "param".toCharArray();
        TAG_PARAM = charArray2;
        char[] charArray3 = "return".toCharArray();
        TAG_RETURN = charArray3;
        char[] charArray4 = "throws".toCharArray();
        TAG_THROWS = charArray4;
        char[] charArray5 = "exception".toCharArray();
        TAG_EXCEPTION = charArray5;
        char[] charArray6 = "see".toCharArray();
        TAG_SEE = charArray6;
        char[] charArray7 = "link".toCharArray();
        TAG_LINK = charArray7;
        char[] charArray8 = "linkplain".toCharArray();
        TAG_LINKPLAIN = charArray8;
        char[] charArray9 = "inheritDoc".toCharArray();
        TAG_INHERITDOC = charArray9;
        char[] charArray10 = "value".toCharArray();
        TAG_VALUE = charArray10;
        char[] charArray11 = "author".toCharArray();
        TAG_AUTHOR = charArray11;
        char[] charArray12 = "code".toCharArray();
        TAG_CODE = charArray12;
        char[] charArray13 = "docRoot".toCharArray();
        TAG_DOC_ROOT = charArray13;
        char[] charArray14 = "literal".toCharArray();
        TAG_LITERAL = charArray14;
        char[] charArray15 = "serial".toCharArray();
        TAG_SERIAL = charArray15;
        char[] charArray16 = "serialData".toCharArray();
        TAG_SERIAL_DATA = charArray16;
        char[] charArray17 = "serialField".toCharArray();
        TAG_SERIAL_FIELD = charArray17;
        char[] charArray18 = "since".toCharArray();
        TAG_SINCE = charArray18;
        char[] charArray19 = "version".toCharArray();
        TAG_VERSION = charArray19;
        char[] charArray20 = "category".toCharArray();
        TAG_CATEGORY = charArray20;
        char[] charArray21 = "systemProperty".toCharArray();
        TAG_SYSTEM_PROPERTY = charArray21;
        char[] charArray22 = "uses".toCharArray();
        TAG_USES = charArray22;
        char[] charArray23 = "provides".toCharArray();
        TAG_PROVIDES = charArray23;
        char[] charArray24 = "hidden".toCharArray();
        TAG_HIDDEN = charArray24;
        char[] charArray25 = FirebaseAnalytics.d.f67690b0.toCharArray();
        TAG_INDEX = charArray25;
        char[] charArray26 = "summary".toCharArray();
        TAG_SUMMARY = charArray26;
        char[] charArray27 = "apiNote".toCharArray();
        TAG_API_NOTE = charArray27;
        char[] charArray28 = "implSpec".toCharArray();
        TAG_IMPL_SPEC = charArray28;
        char[] charArray29 = "implNote".toCharArray();
        TAG_IMPL_NOTE = charArray29;
        TAG_DEPRECATED_LENGTH = charArray.length;
        TAG_PARAM_LENGTH = charArray2.length;
        TAG_RETURN_LENGTH = charArray3.length;
        TAG_THROWS_LENGTH = charArray4.length;
        TAG_EXCEPTION_LENGTH = charArray5.length;
        TAG_SEE_LENGTH = charArray6.length;
        TAG_LINK_LENGTH = charArray7.length;
        TAG_LINKPLAIN_LENGTH = charArray8.length;
        TAG_INHERITDOC_LENGTH = charArray9.length;
        TAG_VALUE_LENGTH = charArray10.length;
        TAG_CATEGORY_LENGTH = charArray20.length;
        TAG_AUTHOR_LENGTH = charArray11.length;
        TAG_SERIAL_LENGTH = charArray15.length;
        TAG_SERIAL_DATA_LENGTH = charArray16.length;
        TAG_SERIAL_FIELD_LENGTH = charArray17.length;
        TAG_SINCE_LENGTH = charArray18.length;
        TAG_VERSION_LENGTH = charArray19.length;
        TAG_CODE_LENGTH = charArray12.length;
        TAG_LITERAL_LENGTH = charArray14.length;
        TAG_DOC_ROOT_LENGTH = charArray13.length;
        TAG_SYSTEM_PROPERTY_LENGTH = charArray21.length;
        TAG_USES_LENGTH = charArray22.length;
        TAG_PROVIDES_LENGTH = charArray23.length;
        TAG_HIDDEN_LENGTH = charArray24.length;
        TAG_INDEX_LENGTH = charArray25.length;
        TAG_SUMMARY_LENGTH = charArray26.length;
        TAG_API_NOTE_LENGTH = charArray27.length;
        TAG_IMPL_SPEC_LENGTH = charArray28.length;
        TAG_IMPL_NOTE_LENGTH = charArray29.length;
        TAG_NAMES = new char[][]{CharOperation.NO_CHAR, charArray, charArray2, charArray3, charArray4, charArray5, charArray6, charArray7, charArray8, charArray9, charArray10, charArray20, charArray11, charArray15, charArray16, charArray17, charArray18, charArray19, charArray12, charArray14, charArray13, charArray21, charArray22, charArray23, charArray24, charArray25, charArray26, charArray27, charArray28, charArray29};
        HREF_TAG = new char[]{'h', 'r', 'e', 'f'};
        char[][][] cArr = {new char[][]{charArray11, charArray, charArray5, charArray2, charArray3, charArray6, charArray19, charArray20}, new char[][]{charArray18}, new char[][]{charArray15, charArray16, charArray17, charArray4}, new char[0], new char[0], new char[0], new char[0], new char[0], new char[][]{charArray27, charArray28, charArray29}, new char[][]{charArray24, charArray22, charArray23}, new char[0], new char[0], new char[0]};
        BLOCK_TAGS = cArr;
        char[][][] cArr2 = {new char[0], new char[0], new char[][]{charArray7}, new char[][]{charArray13}, new char[][]{charArray9, charArray8, charArray10}, new char[][]{charArray12, charArray14}, new char[0], new char[0], new char[0], new char[][]{charArray25}, new char[][]{charArray26}, new char[0], new char[][]{charArray21}};
        INLINE_TAGS = cArr2;
        int length = cArr2.length;
        INLINE_TAGS_LENGTH = length;
        int length2 = cArr.length;
        BLOCK_TAGS_LENGTH = length2;
        ALL_TAGS_LENGTH = length2 + length;
        JAVADOC_TAG_TYPE = new short[]{0, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2};
        PACKAGE_TAGS = new char[][]{charArray6, charArray18, charArray15, charArray11, charArray19, charArray20, charArray7, charArray8, charArray13, charArray10, charArray21, charArray24, charArray25, charArray26, charArray27, charArray28, charArray29};
        COMPILATION_UNIT_TAGS = new char[0];
        CLASS_TAGS = new char[][]{charArray6, charArray18, charArray, charArray15, charArray11, charArray19, charArray2, charArray20, charArray7, charArray8, charArray13, charArray10, charArray12, charArray14, charArray21, charArray24, charArray25, charArray26, charArray27, charArray28, charArray29};
        FIELD_TAGS = new char[][]{charArray6, charArray18, charArray, charArray15, charArray17, charArray20, charArray7, charArray8, charArray13, charArray10, charArray12, charArray14, charArray21, charArray25, charArray24, charArray26, charArray27, charArray28, charArray29};
        METHOD_TAGS = new char[][]{charArray6, charArray18, charArray, charArray2, charArray3, charArray4, charArray5, charArray16, charArray20, charArray7, charArray8, charArray9, charArray13, charArray10, charArray12, charArray14, charArray21, charArray24, charArray25, charArray26, charArray27, charArray28, charArray29};
        MODULE_TAGS = new char[][]{charArray6, charArray18, charArray, charArray15, charArray11, charArray19, charArray20, charArray7, charArray8, charArray13, charArray10, charArray12, charArray14, charArray22, charArray23, charArray24, charArray25, charArray26, charArray27, charArray28, charArray29};
    }
}
