package Mi;

import Bi.O;
import Di.c;
import Di.d;
import Di.e;
import Di.f;
import Ii.L;
import java.io.PrintStream;
import java.math.BigInteger;
import java.security.SecureRandom;
import org.apache.commons.math3.geometry.VectorFormat;
import org.bouncycastle.crypto.CryptoException;

public class b {
    public static BigInteger a(BigInteger bigInteger) {
        O x10 = L.x();
        byte[] byteArray = bigInteger.toByteArray();
        byte[] bArr = new byte[x10.f()];
        x10.update(byteArray, 0, byteArray.length);
        x10.c(bArr, 0);
        return new BigInteger(bArr);
    }

    public static void b(String[] strArr) throws CryptoException {
        Di.b bVar = c.f5221c;
        BigInteger b10 = bVar.b();
        BigInteger c10 = bVar.c();
        BigInteger a10 = bVar.a();
        PrintStream printStream = System.out;
        printStream.println("********* Initialization **********");
        printStream.println("Public parameters for the cyclic group:");
        printStream.println("p (" + b10.bitLength() + " bits): " + b10.toString(16));
        printStream.println("q (" + c10.bitLength() + " bits): " + c10.toString(16));
        printStream.println("g (" + b10.bitLength() + " bits): " + a10.toString(16));
        StringBuilder sb2 = new StringBuilder();
        sb2.append("p mod q = ");
        sb2.append(b10.mod(c10).toString(16));
        printStream.println(sb2.toString());
        printStream.println("g^{q} mod p = " + a10.modPow(c10, b10).toString(16));
        printStream.println("");
        printStream.println("(Secret passwords used by Alice and Bob: \"password\" and \"password\")\n");
        O x10 = L.x();
        SecureRandom secureRandom = new SecureRandom();
        Di.a aVar = new Di.a("alice", "password".toCharArray(), bVar, x10, secureRandom);
        Di.a aVar2 = new Di.a("bob", "password".toCharArray(), bVar, x10, secureRandom);
        d c11 = aVar.c();
        d c12 = aVar2.c();
        printStream.println("************ Round 1 **************");
        printStream.println("Alice sends to Bob: ");
        printStream.println("g^{x1}=" + c11.a().toString(16));
        printStream.println("g^{x2}=" + c11.b().toString(16));
        printStream.println("KP{x1}={" + c11.c()[0].toString(16) + "};{" + c11.c()[1].toString(16) + VectorFormat.DEFAULT_SUFFIX);
        printStream.println("KP{x2}={" + c11.d()[0].toString(16) + "};{" + c11.d()[1].toString(16) + VectorFormat.DEFAULT_SUFFIX);
        printStream.println("");
        printStream.println("Bob sends to Alice: ");
        StringBuilder sb3 = new StringBuilder();
        sb3.append("g^{x3}=");
        sb3.append(c12.a().toString(16));
        printStream.println(sb3.toString());
        printStream.println("g^{x4}=" + c12.b().toString(16));
        printStream.println("KP{x3}={" + c12.c()[0].toString(16) + "};{" + c12.c()[1].toString(16) + VectorFormat.DEFAULT_SUFFIX);
        printStream.println("KP{x4}={" + c12.d()[0].toString(16) + "};{" + c12.d()[1].toString(16) + VectorFormat.DEFAULT_SUFFIX);
        printStream.println("");
        aVar.g(c12);
        printStream.println("Alice checks g^{x4}!=1: OK");
        printStream.println("Alice checks KP{x3}: OK");
        printStream.println("Alice checks KP{x4}: OK");
        printStream.println("");
        aVar2.g(c11);
        printStream.println("Bob checks g^{x2}!=1: OK");
        printStream.println("Bob checks KP{x1},: OK");
        printStream.println("Bob checks KP{x2},: OK");
        printStream.println("");
        e d10 = aVar.d();
        e d11 = aVar2.d();
        printStream.println("************ Round 2 **************");
        printStream.println("Alice sends to Bob: ");
        printStream.println("A=" + d10.a().toString(16));
        printStream.println("KP{x2*s}={" + d10.b()[0].toString(16) + "},{" + d10.b()[1].toString(16) + VectorFormat.DEFAULT_SUFFIX);
        printStream.println("");
        printStream.println("Bob sends to Alice");
        StringBuilder sb4 = new StringBuilder();
        sb4.append("B=");
        sb4.append(d11.a().toString(16));
        printStream.println(sb4.toString());
        printStream.println("KP{x4*s}={" + d11.b()[0].toString(16) + "},{" + d11.b()[1].toString(16) + VectorFormat.DEFAULT_SUFFIX);
        printStream.println("");
        aVar.h(d11);
        printStream.println("Alice checks KP{x4*s}: OK\n");
        aVar2.h(d10);
        printStream.println("Bob checks KP{x2*s}: OK\n");
        BigInteger a11 = aVar.a();
        BigInteger a12 = aVar2.a();
        printStream.println("********* After round 2 ***********");
        printStream.println("Alice computes key material \t K=" + a11.toString(16));
        printStream.println("Bob computes key material \t K=" + a12.toString(16));
        printStream.println();
        a(a11);
        a(a12);
        f e10 = aVar.e(a11);
        f e11 = aVar2.e(a12);
        printStream.println("************ Round 3 **************");
        printStream.println("Alice sends to Bob: ");
        printStream.println("MacTag=" + e10.a().toString(16));
        printStream.println("");
        printStream.println("Bob sends to Alice: ");
        printStream.println("MacTag=" + e11.a().toString(16));
        printStream.println("");
        aVar.i(e11, a11);
        printStream.println("Alice checks MacTag: OK\n");
        aVar2.i(e10, a12);
        printStream.println("Bob checks MacTag: OK\n");
        printStream.println();
        printStream.println("MacTags validated, therefore the keying material matches.");
    }
}
