package com.google.android.gms.measurement.internal;

import com.google.firebase.analytics.FirebaseAnalytics;

public final class C12259b4 {

    public static final String[] f63020a = {"ga_conversion", "engagement_time_msec", "exposure_time", "ad_event_id", "ad_unit_id", "ga_error", "ga_error_value", "ga_error_length", "ga_event_origin", "ga_screen", "ga_screen_class", "ga_screen_id", "ga_previous_screen", "ga_previous_class", "ga_previous_id", "manual_tracking", "message_device_time", "message_id", "message_name", "message_time", "message_tracking_id", "message_type", "previous_app_version", "previous_os_version", "topic", "update_with_analytics", "previous_first_open_count", "system_app", "system_app_update", "previous_install_count", "ga_event_id", "ga_extra_params_ct", "ga_group_name", "ga_list_length", "ga_index", "ga_event_name", "campaign_info_source", "cached_campaign", "deferred_analytics_collection", "ga_session_number", "ga_session_id", "campaign_extra_referrer", "app_in_background", "firebase_feature_rollouts", "customer_type", "firebase_conversion", "firebase_error", "firebase_error_value", "firebase_error_length", "firebase_event_origin", "firebase_screen", "firebase_screen_class", "firebase_screen_id", "firebase_previous_screen", "firebase_previous_class", "firebase_previous_id", "session_number", "session_id"};

    public static final String[] f63021b = {"_c", "_et", "_xt", "_aeid", "_ai", "_err", "_ev", "_el", "_o", "_sn", "_sc", "_si", "_pn", "_pc", "_pi", "_mst", "_ndt", "_nmid", "_nmn", "_nmt", "_nmtid", "_nmc", "_pv", "_po", "_nt", "_uwa", "_pfo", "_sys", "_sysu", "_pin", "_eid", "_epc", "_gn", "_ll", "_i", "_en", "_cis", "_cc", "_dac", "_sno", "_sid", "_cer", "_aib", "_ffr", "_ct", "_c", "_err", "_ev", "_el", "_o", "_sn", "_sc", "_si", "_pn", "_pc", "_pi", "_sno", "_sid"};

    public static final String[] f63022c = {FirebaseAnalytics.d.f67706j0};

    public static final String[] f63023d = {FirebaseAnalytics.d.f67688a0, FirebaseAnalytics.d.f67705j, FirebaseAnalytics.d.f67685Y, FirebaseAnalytics.d.f67686Z, FirebaseAnalytics.d.f67703i, "_ct", FirebaseAnalytics.d.f67692c0, FirebaseAnalytics.d.f67690b0, FirebaseAnalytics.d.f67719q, FirebaseAnalytics.d.f67683W, FirebaseAnalytics.d.f67717p, FirebaseAnalytics.d.f67694d0, FirebaseAnalytics.d.f67696e0, FirebaseAnalytics.d.f67698f0, FirebaseAnalytics.d.f67700g0, FirebaseAnalytics.d.f67704i0, FirebaseAnalytics.d.f67702h0, FirebaseAnalytics.d.f67721r, FirebaseAnalytics.d.f67684X, FirebaseAnalytics.d.f67708k0, FirebaseAnalytics.d.f67710l0, FirebaseAnalytics.d.f67662B, FirebaseAnalytics.d.f67712m0, FirebaseAnalytics.d.f67714n0, FirebaseAnalytics.d.f67663C, FirebaseAnalytics.d.f67665E, FirebaseAnalytics.d.f67720q0, FirebaseAnalytics.d.f67669I, FirebaseAnalytics.d.f67666F, "value", "item_list", "checkout_step", "checkout_option", "item_location_id"};
}
