package org.eclipse.jdt.internal.codeassist.impl;

import android.provider.CallLog;
import android.provider.Telephony;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import org.eclipse.jdt.core.IClasspathAttribute;

public interface Keywords {
    public static final int COUNT = 50;
    public static final char[] ABSTRACT = "abstract".toCharArray();
    public static final char[] ASSERT = "assert".toCharArray();
    public static final char[] BREAK = "break".toCharArray();
    public static final char[] CASE = "case".toCharArray();
    public static final char[] CATCH = "catch".toCharArray();
    public static final char[] CLASS = "class".toCharArray();
    public static final char[] CONTINUE = "continue".toCharArray();
    public static final char[] DEFAULT = "default".toCharArray();
    public static final char[] DO = "do".toCharArray();
    public static final char[] ELSE = "else".toCharArray();
    public static final char[] ENUM = "enum".toCharArray();
    public static final char[] EXTENDS = "extends".toCharArray();
    public static final char[] EXPORTS = "exports".toCharArray();
    public static final char[] FINAL = "final".toCharArray();
    public static final char[] FINALLY = "finally".toCharArray();
    public static final char[] FOR = "for".toCharArray();
    public static final char[] IF = "if".toCharArray();
    public static final char[] IMPLEMENTS = "implements".toCharArray();
    public static final char[] IMPORT = "import".toCharArray();
    public static final char[] MODULE = IClasspathAttribute.MODULE.toCharArray();
    public static final char[] INSTANCEOF = "instanceof".toCharArray();
    public static final char[] INTERFACE = "interface".toCharArray();
    public static final char[] NATIVE = "native".toCharArray();
    public static final char[] NEW = CallLog.Calls.NEW.toCharArray();
    public static final char[] OPENS = "opens".toCharArray();
    public static final char[] PACKAGE = Telephony.Sms.Intents.EXTRA_PACKAGE_NAME.toCharArray();
    public static final char[] PRIVATE = "private".toCharArray();
    public static final char[] PROTECTED = "protected".toCharArray();
    public static final char[] PROVIDES = "provides".toCharArray();
    public static final char[] PUBLIC = "public".toCharArray();
    public static final char[] REQUIRES = "requires".toCharArray();
    public static final char[] RETURN = "return".toCharArray();
    public static final char[] STATIC = "static".toCharArray();
    public static final char[] STRICTFP = "strictfp".toCharArray();
    public static final char[] SUPER = "super".toCharArray();
    public static final char[] SWITCH = "switch".toCharArray();
    public static final char[] SYNCHRONIZED = "synchronized".toCharArray();
    public static final char[] THIS = "this".toCharArray();
    public static final char[] THROW = "throw".toCharArray();
    public static final char[] THROWS = "throws".toCharArray();
    public static final char[] TO = TypedValues.TransitionType.S_TO.toCharArray();
    public static final char[] TRANSIENT = "transient".toCharArray();
    public static final char[] TRY = "try".toCharArray();
    public static final char[] USES = "uses".toCharArray();
    public static final char[] VOLATILE = "volatile".toCharArray();
    public static final char[] WHILE = "while".toCharArray();
    public static final char[] WITH = "with".toCharArray();
    public static final char[] TRUE = "true".toCharArray();
    public static final char[] FALSE = "false".toCharArray();
    public static final char[] NULL = "null".toCharArray();
    public static final char[] VAR = "var".toCharArray();
}
