package defpackage;

import com.bumptech.glide.load.engine.GlideException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.List;
import org.luaj.vm2.Globals;
import org.luaj.vm2.lib.jse.JsePlatform;
import org.luaj.vm2.luajc.LuaJC;

public class luajc {
    private static final String usage = "usage: java -cp luaj-jse.jar,bcel-5.2.jar luajc [options] fileordir [, fileordir ...]\nAvailable options are:\n  -        process stdin\n  -s src\tsource directory\n  -d dir\tdestination directory\n  -p pkg\tpackage prefix to apply to all classes\n  -m\t\tgenerate main(String[]) function for JSE\n  -r\t\trecursively compile all\n  -l\t\tload classes to verify generated bytecode\n  -c enc  \tuse the supplied encoding 'enc' for input files\n  -v   \tverbose\n";
    private static final String version = "Luaj-jse 3.0.1 Copyright (C) 2012 luaj.org";
    private String destdir;
    private String encoding;
    private List files = new ArrayList();
    private boolean genmain;
    private Globals globals;
    private boolean loadclasses;
    private String pkgprefix;
    private boolean recurse;
    private String srcdir;
    private boolean verbose;

    public class a {

        public String f96641a;

        public String f96642b;

        public File f96643c;

        public File f96644d;

        public String f96645e;

        public a(File file, File file2, String str) {
            String str2;
            String str3;
            this.f96643c = file2;
            String replace = str != null ? str.replace('.', '/') : null;
            if (replace != null) {
                StringBuffer stringBuffer = new StringBuffer();
                stringBuffer.append(luajc.this.destdir);
                stringBuffer.append("/");
                stringBuffer.append(replace);
                str2 = stringBuffer.toString();
            } else {
                str2 = luajc.this.destdir;
            }
            this.f96645e = str;
            StringBuffer stringBuffer2 = new StringBuffer();
            String str4 = "";
            if (replace != null) {
                StringBuffer stringBuffer3 = new StringBuffer();
                stringBuffer3.append(replace);
                stringBuffer3.append("/");
                str3 = stringBuffer3.toString();
            } else {
                str3 = "";
            }
            stringBuffer2.append(str3);
            stringBuffer2.append(this.f96643c.getName());
            this.f96642b = stringBuffer2.toString();
            StringBuffer stringBuffer4 = new StringBuffer();
            if (replace != null) {
                StringBuffer stringBuffer5 = new StringBuffer();
                stringBuffer5.append(replace);
                stringBuffer5.append("/");
                str4 = stringBuffer5.toString();
            }
            stringBuffer4.append(str4);
            stringBuffer4.append(this.f96643c.getName().substring(0, this.f96643c.getName().lastIndexOf(46)));
            this.f96641a = stringBuffer4.toString();
            this.f96643c = file2;
            this.f96644d = new File(str2);
        }
    }

    public static final class b extends ClassLoader {

        public final Hashtable f96647a;

        public b(Hashtable hashtable) {
            this.f96647a = hashtable;
        }

        @Override
        public Class findClass(String str) throws ClassNotFoundException {
            byte[] bArr = (byte[]) this.f96647a.get(str);
            return bArr != null ? defineClass(str, bArr, 0, bArr.length) : super.findClass(str);
        }
    }

    private luajc(String[] strArr) throws IOException {
        this.srcdir = ".";
        this.destdir = ".";
        this.genmain = false;
        this.recurse = false;
        this.verbose = false;
        this.loadclasses = false;
        this.encoding = null;
        this.pkgprefix = null;
        ArrayList arrayList = new ArrayList();
        int i10 = 0;
        while (i10 < strArr.length) {
            if (strArr[i10].startsWith("-")) {
                char charAt = strArr[i10].charAt(1);
                if (charAt == 'c') {
                    i10++;
                    if (i10 >= strArr.length) {
                        usageExit();
                    }
                    this.encoding = strArr[i10];
                } else if (charAt == 'd') {
                    i10++;
                    if (i10 >= strArr.length) {
                        usageExit();
                    }
                    this.destdir = strArr[i10];
                } else if (charAt == 'l') {
                    this.loadclasses = true;
                } else if (charAt == 'm') {
                    this.genmain = true;
                } else if (charAt == 'p') {
                    i10++;
                    if (i10 >= strArr.length) {
                        usageExit();
                    }
                    this.pkgprefix = strArr[i10];
                } else if (charAt == 'v') {
                    this.verbose = true;
                } else if (charAt == 'r') {
                    this.recurse = true;
                } else if (charAt != 's') {
                    usageExit();
                } else {
                    i10++;
                    if (i10 >= strArr.length) {
                        usageExit();
                    }
                    this.srcdir = strArr[i10];
                }
            } else {
                arrayList.add(strArr[i10]);
            }
            i10++;
        }
        if (this.verbose) {
            PrintStream printStream = System.out;
            printStream.println(version);
            StringBuffer stringBuffer = new StringBuffer();
            stringBuffer.append("srcdir: ");
            stringBuffer.append(this.srcdir);
            printStream.println(stringBuffer.toString());
            StringBuffer stringBuffer2 = new StringBuffer();
            stringBuffer2.append("destdir: ");
            stringBuffer2.append(this.destdir);
            printStream.println(stringBuffer2.toString());
            StringBuffer stringBuffer3 = new StringBuffer();
            stringBuffer3.append("files: ");
            stringBuffer3.append((Object) arrayList);
            printStream.println(stringBuffer3.toString());
            StringBuffer stringBuffer4 = new StringBuffer();
            stringBuffer4.append("recurse: ");
            stringBuffer4.append(this.recurse);
            printStream.println(stringBuffer4.toString());
        }
        if (arrayList.size() <= 0) {
            System.err.println(usage);
            System.exit(-1);
        }
        for (int i11 = 0; i11 < arrayList.size(); i11++) {
            StringBuffer stringBuffer5 = new StringBuffer();
            stringBuffer5.append(this.srcdir);
            stringBuffer5.append("/");
            stringBuffer5.append(arrayList.get(i11));
            collectFiles(stringBuffer5.toString());
        }
        if (this.files.size() <= 0) {
            PrintStream printStream2 = System.err;
            StringBuffer stringBuffer6 = new StringBuffer();
            stringBuffer6.append("no files found in ");
            stringBuffer6.append((Object) arrayList);
            printStream2.println(stringBuffer6.toString());
            System.exit(-1);
        }
        this.globals = JsePlatform.standardGlobals();
        int size = this.files.size();
        for (int i12 = 0; i12 < size; i12++) {
            processFile((a) this.files.get(i12));
        }
    }

    private void collectFiles(String str) {
        File parentFile;
        File file = new File(str);
        if (file.isDirectory() && this.recurse) {
            scandir(file, this.pkgprefix);
        } else {
            if (!file.isFile() || (parentFile = file.getAbsoluteFile().getParentFile()) == null) {
                return;
            }
            scanfile(parentFile, file, this.pkgprefix);
        }
    }

    public static void main(String[] strArr) throws IOException {
        new luajc(strArr);
    }

    private void processFile(a aVar) {
        String str;
        aVar.f96644d.mkdirs();
        try {
            if (this.verbose) {
                PrintStream printStream = System.out;
                StringBuffer stringBuffer = new StringBuffer();
                stringBuffer.append("chunk=");
                stringBuffer.append(aVar.f96641a);
                stringBuffer.append(" srcfile=");
                stringBuffer.append(aVar.f96642b);
                printStream.println(stringBuffer.toString());
            }
            FileInputStream fileInputStream = new FileInputStream(aVar.f96643c);
            Hashtable compileAll = this.encoding != null ? LuaJC.instance.compileAll(new InputStreamReader(fileInputStream, this.encoding), aVar.f96641a, aVar.f96642b, this.globals, this.genmain) : LuaJC.instance.compileAll(fileInputStream, aVar.f96641a, aVar.f96642b, this.globals, this.genmain);
            fileInputStream.close();
            Enumeration keys = compileAll.keys();
            while (keys.hasMoreElements()) {
                String str2 = (String) keys.nextElement();
                byte[] bArr = (byte[]) compileAll.get(str2);
                String str3 = "";
                if (str2.indexOf(47) >= 0) {
                    StringBuffer stringBuffer2 = new StringBuffer();
                    if (this.destdir != null) {
                        StringBuffer stringBuffer3 = new StringBuffer();
                        stringBuffer3.append(this.destdir);
                        stringBuffer3.append("/");
                        str = stringBuffer3.toString();
                    } else {
                        str = "";
                    }
                    stringBuffer2.append(str);
                    stringBuffer2.append(str2.substring(0, str2.lastIndexOf(47)));
                    new File(stringBuffer2.toString()).mkdirs();
                }
                StringBuffer stringBuffer4 = new StringBuffer();
                if (this.destdir != null) {
                    StringBuffer stringBuffer5 = new StringBuffer();
                    stringBuffer5.append(this.destdir);
                    stringBuffer5.append("/");
                    str3 = stringBuffer5.toString();
                }
                stringBuffer4.append(str3);
                stringBuffer4.append(str2);
                stringBuffer4.append(".class");
                String stringBuffer6 = stringBuffer4.toString();
                if (this.verbose) {
                    PrintStream printStream2 = System.out;
                    StringBuffer stringBuffer7 = new StringBuffer();
                    stringBuffer7.append(GlideException.a.f59088e);
                    stringBuffer7.append(stringBuffer6);
                    stringBuffer7.append(" (");
                    stringBuffer7.append(bArr.length);
                    stringBuffer7.append(" bytes)");
                    printStream2.println(stringBuffer7.toString());
                }
                FileOutputStream fileOutputStream = new FileOutputStream(stringBuffer6);
                fileOutputStream.write(bArr);
                fileOutputStream.close();
            }
            if (this.loadclasses) {
                b bVar = new b(compileAll);
                Enumeration keys2 = compileAll.keys();
                while (keys2.hasMoreElements()) {
                    String str4 = (String) keys2.nextElement();
                    try {
                        Object newInstance = bVar.loadClass(str4).newInstance();
                        if (this.verbose) {
                            PrintStream printStream3 = System.out;
                            StringBuffer stringBuffer8 = new StringBuffer();
                            stringBuffer8.append("    loaded ");
                            stringBuffer8.append(str4);
                            stringBuffer8.append(" as ");
                            stringBuffer8.append(newInstance);
                            printStream3.println(stringBuffer8.toString());
                        }
                    } catch (Exception e10) {
                        System.out.flush();
                        PrintStream printStream4 = System.err;
                        StringBuffer stringBuffer9 = new StringBuffer();
                        stringBuffer9.append("    failed to load ");
                        stringBuffer9.append(str4);
                        stringBuffer9.append(": ");
                        stringBuffer9.append((Object) e10);
                        printStream4.println(stringBuffer9.toString());
                        printStream4.flush();
                    }
                }
            }
        } catch (Exception e11) {
            PrintStream printStream5 = System.err;
            StringBuffer stringBuffer10 = new StringBuffer();
            stringBuffer10.append("    failed to load ");
            stringBuffer10.append(aVar.f96642b);
            stringBuffer10.append(": ");
            stringBuffer10.append((Object) e11);
            printStream5.println(stringBuffer10.toString());
            e11.printStackTrace(printStream5);
            printStream5.flush();
        }
    }

    private void scandir(File file, String str) {
        for (File file2 : file.listFiles()) {
            scanfile(file, file2, str);
        }
    }

    private void scanfile(File file, File file2, String str) {
        String name;
        if (file2.exists()) {
            if (!file2.isDirectory() || !this.recurse) {
                if (file2.isFile() && file2.getName().endsWith(".lua")) {
                    this.files.add(new a(file, file2, str));
                    return;
                }
                return;
            }
            if (str != null) {
                StringBuffer stringBuffer = new StringBuffer();
                stringBuffer.append(str);
                stringBuffer.append(".");
                stringBuffer.append(file2.getName());
                name = stringBuffer.toString();
            } else {
                name = file2.getName();
            }
            scandir(file2, name);
        }
    }

    private static void usageExit() {
        System.out.println(usage);
        System.exit(-1);
    }
}
