package D0;

import androidx.annotation.NonNull;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.p;
import com.google.android.gms.common.api.u;
import java.util.concurrent.TimeUnit;

public final class C2478x0<R extends com.google.android.gms.common.api.u> extends com.google.android.gms.common.api.p<R> {

    public final Status f4720a;

    public C2478x0(Status status) {
        G0.A.s(status, "Status must not be null");
        G0.A.b(!status.x0(), "Status must not be success");
        this.f4720a = status;
    }

    @Override
    public final void c(@NonNull p.a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override
    @NonNull
    public final R d() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override
    @NonNull
    public final R e(long j10, @NonNull TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override
    public final void f() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override
    public final boolean g() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override
    public final void h(@NonNull com.google.android.gms.common.api.v<? super R> vVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override
    public final void i(@NonNull com.google.android.gms.common.api.v<? super R> vVar, long j10, @NonNull TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override
    @G0.F
    @NonNull
    public final <S extends com.google.android.gms.common.api.u> com.google.android.gms.common.api.z<S> j(@NonNull com.google.android.gms.common.api.x<? super R, ? extends S> xVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @NonNull
    public final Status k() {
        return this.f4720a;
    }
}
