#!/usr/bin/env python3
"""Recompile Interaction Java and enforce the real APK ABI before accepting the output.

The project is reconstructed from a decompiled APK, so javac has to compile Interaction
sources against temporary stubs. Those stubs intentionally use some JADX-readable names
and can drift from the descriptors that ART actually resolves at runtime.

This wrapper is the supported local recompile entrypoint. It mirrors the safety passes
used by the APK build workflow:

1. compile Java -> DEX -> smali;
2. remove writes to the fake Transform position-cache stub;
3. normalize verified JADX aliases and return-type descriptors;
4. verify every generated Interaction method/field reference against the original APK.

Do not treat a successful javac/D8 run alone as proof that the generated bytecode is
runtime-compatible.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

RECOMPILE = HERE / "recompile_interaction_dex.py"
FIX_TRANSFORM_POSITION = HERE / "fix_interaction_transform_position_smali.py"
FIX_ALIASES = HERE / "fix_interaction_smali_aliases.py"
VERIFY_ABI = HERE / "verify_interaction_smali_abi.py"

APKTOOL_ROOT = ROOT / "extracted" / "apktool_base"
SMALI_ROOT = APKTOOL_ROOT / "smali_classes10"
REPORT = ROOT / "interaction-abi-report.txt"


def run(cmd: list[object], label: str) -> None:
    print(f"\n== {label} ==")
    result = subprocess.run([str(x) for x in cmd])
    if result.returncode != 0:
        raise SystemExit(result.returncode)


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        print(f"Missing {label}: {path}", file=sys.stderr)
        raise SystemExit(2)


def main() -> int:
    require_file(RECOMPILE, "Interaction compiler")
    require_file(FIX_TRANSFORM_POSITION, "Transform ABI fixer")
    require_file(FIX_ALIASES, "Interaction alias/descriptor fixer")
    require_file(VERIFY_ABI, "Interaction ABI verifier")

    if not APKTOOL_ROOT.is_dir():
        print(f"Missing apktool root: {APKTOOL_ROOT}", file=sys.stderr)
        return 2

    run([sys.executable, RECOMPILE], "1/4 Compile Interaction Java to smali")
    run(
        [sys.executable, FIX_TRANSFORM_POSITION, SMALI_ROOT],
        "2/4 Rewrite unsafe Transform position bytecode",
    )
    run(
        [sys.executable, FIX_ALIASES, SMALI_ROOT],
        "3/4 Normalize JADX aliases and verified ABI descriptors",
    )
    run(
        [
            sys.executable,
            VERIFY_ABI,
            APKTOOL_ROOT,
            "--interaction-root",
            SMALI_ROOT,
            "--report",
            REPORT,
        ],
        "4/4 Verify generated Interaction smali against original APK ABI",
    )

    print("\nSAFE INTERACTION RECOMPILE COMPLETED")
    print(f"ABI report: {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
