package Kj;

import android.security.keystore.KeyProperties;
import bi.InterfaceC3890b;
import bk.AbstractC3896b;
import java.util.HashMap;
import java.util.Map;
import mj.InterfaceC14273a;
import nj.InterfaceC14453b;
import oh.C14549x;
import org.bouncycastle.jcajce.provider.asymmetric.ec.j;
import pj.InterfaceC15005a;

public class g {

    public static final String f11436a = "org.bouncycastle.jcajce.provider.asymmetric.ec.";

    public static final Map<String, String> f11437b;

    public static class a extends AbstractC3896b {
        @Override
        public void a(Tj.a aVar) {
            aVar.d("AlgorithmParameters.EC", "org.bouncycastle.jcajce.provider.asymmetric.ec.AlgorithmParametersSpi");
            aVar.b("KeyAgreement.ECDH", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DH", g.f11437b);
            aVar.b("KeyAgreement.ECDHC", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHC", g.f11437b);
            aVar.b("KeyAgreement.ECCDH", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHC", g.f11437b);
            aVar.b("KeyAgreement.ECCDHU", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUC", g.f11437b);
            aVar.b("KeyAgreement.ECDHWITHSHA1KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA1KDFAndSharedInfo", g.f11437b);
            aVar.b("KeyAgreement.ECCDHWITHSHA1KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA1KDFAndSharedInfo", g.f11437b);
            aVar.b("KeyAgreement.ECDHWITHSHA224KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA224KDFAndSharedInfo", g.f11437b);
            aVar.b("KeyAgreement.ECCDHWITHSHA224KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA224KDFAndSharedInfo", g.f11437b);
            aVar.b("KeyAgreement.ECDHWITHSHA256KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA256KDFAndSharedInfo", g.f11437b);
            aVar.b("KeyAgreement.ECCDHWITHSHA256KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA256KDFAndSharedInfo", g.f11437b);
            aVar.b("KeyAgreement.ECDHWITHSHA384KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA384KDFAndSharedInfo", g.f11437b);
            aVar.b("KeyAgreement.ECCDHWITHSHA384KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA384KDFAndSharedInfo", g.f11437b);
            aVar.b("KeyAgreement.ECDHWITHSHA512KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA512KDFAndSharedInfo", g.f11437b);
            aVar.b("KeyAgreement.ECCDHWITHSHA512KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA512KDFAndSharedInfo", g.f11437b);
            C14549x c14549x = ki.r.f95353v6;
            aVar.i("KeyAgreement", c14549x, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA1KDFAndSharedInfo", g.f11437b);
            C14549x c14549x2 = ki.r.f95355w6;
            aVar.i("KeyAgreement", c14549x2, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA1KDFAndSharedInfo", g.f11437b);
            C14549x c14549x3 = Zh.d.f31275J;
            aVar.i("KeyAgreement", c14549x3, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA224KDFAndSharedInfo", g.f11437b);
            C14549x c14549x4 = Zh.d.f31279N;
            aVar.i("KeyAgreement", c14549x4, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA224KDFAndSharedInfo", g.f11437b);
            C14549x c14549x5 = Zh.d.f31276K;
            aVar.i("KeyAgreement", c14549x5, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA256KDFAndSharedInfo", g.f11437b);
            C14549x c14549x6 = Zh.d.f31280O;
            aVar.i("KeyAgreement", c14549x6, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA256KDFAndSharedInfo", g.f11437b);
            C14549x c14549x7 = Zh.d.f31277L;
            aVar.i("KeyAgreement", c14549x7, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA384KDFAndSharedInfo", g.f11437b);
            C14549x c14549x8 = Zh.d.f31281P;
            aVar.i("KeyAgreement", c14549x8, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA384KDFAndSharedInfo", g.f11437b);
            C14549x c14549x9 = Zh.d.f31278M;
            aVar.i("KeyAgreement", c14549x9, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA512KDFAndSharedInfo", g.f11437b);
            C14549x c14549x10 = Zh.d.f31282Q;
            aVar.i("KeyAgreement", c14549x10, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA512KDFAndSharedInfo", g.f11437b);
            aVar.b("KeyAgreement.ECCDHWITHSHA1CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA1CKDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHWITHSHA256CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA256CKDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHWITHSHA384CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA384CKDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHWITHSHA512CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA512CKDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHUWITHSHA1CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA1CKDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHUWITHSHA224CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA224CKDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHUWITHSHA256CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA256CKDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHUWITHSHA384CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA384CKDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHUWITHSHA512CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA512CKDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHUWITHSHA1KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA1KDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHUWITHSHA224KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA224KDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHUWITHSHA256KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA256KDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHUWITHSHA384KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA384KDF", g.f11437b);
            aVar.b("KeyAgreement.ECCDHUWITHSHA512KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA512KDF", g.f11437b);
            aVar.b("KeyAgreement.ECKAEGWITHSHA1KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA1KDF", g.f11437b);
            aVar.b("KeyAgreement.ECKAEGWITHSHA224KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA224KDF", g.f11437b);
            aVar.b("KeyAgreement.ECKAEGWITHSHA256KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA256KDF", g.f11437b);
            aVar.b("KeyAgreement.ECKAEGWITHSHA384KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA384KDF", g.f11437b);
            aVar.b("KeyAgreement.ECKAEGWITHSHA512KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA512KDF", g.f11437b);
            aVar.i("KeyAgreement", InterfaceC14273a.f97140q, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA1KDF", g.f11437b);
            aVar.i("KeyAgreement", InterfaceC14273a.f97141r, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA224KDF", g.f11437b);
            aVar.i("KeyAgreement", InterfaceC14273a.f97142s, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA256KDF", g.f11437b);
            aVar.i("KeyAgreement", InterfaceC14273a.f97143t, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA384KDF", g.f11437b);
            aVar.i("KeyAgreement", InterfaceC14273a.f97144u, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA512KDF", g.f11437b);
            aVar.i("KeyAgreement", InterfaceC14273a.f97145v, "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithRIPEMD160KDF", g.f11437b);
            aVar.b("KeyAgreement.ECKAEGWITHRIPEMD160KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithRIPEMD160KDF", g.f11437b);
            C14549x c14549x11 = ki.r.f95305I5;
            l(aVar, c14549x11, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            l(aVar, c14549x, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            l(aVar, c14549x2, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            l(aVar, c14549x3, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            l(aVar, c14549x4, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            l(aVar, c14549x5, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            l(aVar, c14549x6, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            l(aVar, c14549x7, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            l(aVar, c14549x8, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            l(aVar, c14549x9, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            l(aVar, c14549x10, KeyProperties.KEY_ALGORITHM_EC, new j.a());
            n(aVar, c14549x11, KeyProperties.KEY_ALGORITHM_EC);
            n(aVar, c14549x, KeyProperties.KEY_ALGORITHM_EC);
            n(aVar, c14549x2, KeyProperties.KEY_ALGORITHM_EC);
            n(aVar, c14549x3, KeyProperties.KEY_ALGORITHM_EC);
            n(aVar, c14549x4, KeyProperties.KEY_ALGORITHM_EC);
            n(aVar, c14549x5, KeyProperties.KEY_ALGORITHM_EC);
            n(aVar, c14549x6, KeyProperties.KEY_ALGORITHM_EC);
            n(aVar, c14549x7, KeyProperties.KEY_ALGORITHM_EC);
            n(aVar, c14549x8, KeyProperties.KEY_ALGORITHM_EC);
            n(aVar, c14549x9, KeyProperties.KEY_ALGORITHM_EC);
            n(aVar, c14549x10, KeyProperties.KEY_ALGORITHM_EC);
            if (!org.bouncycastle.util.q.f("org.bouncycastle.ec.disable_mqv")) {
                aVar.b("KeyAgreement.ECMQV", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQV", g.f11437b);
                aVar.b("KeyAgreement.ECMQVWITHSHA1CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA1CKDF", g.f11437b);
                aVar.b("KeyAgreement.ECMQVWITHSHA224CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA224CKDF", g.f11437b);
                aVar.b("KeyAgreement.ECMQVWITHSHA256CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA256CKDF", g.f11437b);
                aVar.b("KeyAgreement.ECMQVWITHSHA384CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA384CKDF", g.f11437b);
                aVar.b("KeyAgreement.ECMQVWITHSHA512CKDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA512CKDF", g.f11437b);
                aVar.b("KeyAgreement.ECMQVWITHSHA1KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA1KDF", g.f11437b);
                aVar.b("KeyAgreement.ECMQVWITHSHA224KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA224KDF", g.f11437b);
                aVar.b("KeyAgreement.ECMQVWITHSHA256KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA256KDF", g.f11437b);
                aVar.b("KeyAgreement.ECMQVWITHSHA384KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA384KDF", g.f11437b);
                aVar.b("KeyAgreement.ECMQVWITHSHA512KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA512KDF", g.f11437b);
                StringBuilder sb2 = new StringBuilder();
                sb2.append("KeyAgreement.");
                C14549x c14549x12 = ki.r.f95357x6;
                sb2.append((Object) c14549x12);
                aVar.b(sb2.toString(), "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA1KDFAndSharedInfo", g.f11437b);
                StringBuilder sb3 = new StringBuilder();
                sb3.append("KeyAgreement.");
                C14549x c14549x13 = Zh.d.f31283R;
                sb3.append((Object) c14549x13);
                aVar.b(sb3.toString(), "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA224KDFAndSharedInfo", g.f11437b);
                StringBuilder sb4 = new StringBuilder();
                sb4.append("KeyAgreement.");
                C14549x c14549x14 = Zh.d.f31284S;
                sb4.append((Object) c14549x14);
                aVar.b(sb4.toString(), "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA256KDFAndSharedInfo", g.f11437b);
                StringBuilder sb5 = new StringBuilder();
                sb5.append("KeyAgreement.");
                C14549x c14549x15 = Zh.d.f31285T;
                sb5.append((Object) c14549x15);
                aVar.b(sb5.toString(), "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA384KDFAndSharedInfo", g.f11437b);
                StringBuilder sb6 = new StringBuilder();
                sb6.append("KeyAgreement.");
                C14549x c14549x16 = Zh.d.f31286U;
                sb6.append((Object) c14549x16);
                aVar.b(sb6.toString(), "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA512KDFAndSharedInfo", g.f11437b);
                l(aVar, c14549x12, "ECMQV", new j.g());
                n(aVar, c14549x12, KeyProperties.KEY_ALGORITHM_EC);
                l(aVar, c14549x13, "ECMQV", new j.g());
                n(aVar, c14549x13, KeyProperties.KEY_ALGORITHM_EC);
                l(aVar, c14549x14, "ECMQV", new j.g());
                n(aVar, c14549x14, KeyProperties.KEY_ALGORITHM_EC);
                l(aVar, c14549x15, "ECMQV", new j.g());
                n(aVar, c14549x15, KeyProperties.KEY_ALGORITHM_EC);
                l(aVar, c14549x16, "ECMQV", new j.g());
                n(aVar, c14549x16, KeyProperties.KEY_ALGORITHM_EC);
                aVar.d("KeyFactory.ECMQV", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi$ECMQV");
                aVar.d("KeyPairGenerator.ECMQV", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECMQV");
            }
            aVar.d("KeyFactory.EC", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi$EC");
            aVar.d("KeyFactory.ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi$ECDSA");
            aVar.d("KeyFactory.ECDH", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi$ECDH");
            aVar.d("KeyFactory.ECDHC", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi$ECDHC");
            aVar.d("KeyPairGenerator.EC", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC");
            aVar.d("KeyPairGenerator.ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECDSA");
            aVar.d("KeyPairGenerator.ECDH", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECDH");
            aVar.d("KeyPairGenerator.ECDHWITHSHA1KDF", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECDH");
            aVar.d("KeyPairGenerator.ECDHC", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECDHC");
            aVar.d("KeyPairGenerator.ECIES", "org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECDH");
            aVar.b("Cipher.ECIES", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIES", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA1", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIES", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA1", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIES", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA256", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA256", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA256", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA256", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA384", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA384", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA384", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA384", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA512", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA512", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA512", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA512", g.f11437b);
            aVar.b("Cipher.ECIESwithAES-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithAESCBC", g.f11437b);
            aVar.b("Cipher.ECIESWITHAES-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithAESCBC", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA1andAES-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithAESCBC", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA1ANDAES-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithAESCBC", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA256andAES-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA256andAESCBC", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA256ANDAES-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA256andAESCBC", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA384andAES-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA384andAESCBC", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA384ANDAES-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA384andAESCBC", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA512andAES-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA512andAESCBC", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA512ANDAES-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA512andAESCBC", g.f11437b);
            aVar.b("Cipher.ECIESwithDESEDE-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithDESedeCBC", g.f11437b);
            aVar.b("Cipher.ECIESWITHDESEDE-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithDESedeCBC", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA1andDESEDE-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithDESedeCBC", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA1ANDDESEDE-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithDESedeCBC", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA256andDESEDE-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA256andDESedeCBC", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA256ANDDESEDE-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA256andDESedeCBC", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA384andDESEDE-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA384andDESedeCBC", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA384ANDDESEDE-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA384andDESedeCBC", g.f11437b);
            aVar.b("Cipher.ECIESwithSHA512andDESEDE-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA512andDESedeCBC", g.f11437b);
            aVar.b("Cipher.ECIESWITHSHA512ANDDESEDE-CBC", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithSHA512andDESedeCBC", g.f11437b);
            aVar.b("Cipher.ETSIKEMWITHSHA256", "org.bouncycastle.jcajce.provider.asymmetric.ec.IESKEMCipher$KEMwithSHA256", g.f11437b);
            aVar.b("Signature.ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSA", g.f11437b);
            aVar.b("Signature.NONEwithECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSAnone", g.f11437b);
            aVar.d("Alg.Alias.Signature.SHA1withECDSA", "ECDSA");
            aVar.d("Alg.Alias.Signature.ECDSAwithSHA1", "ECDSA");
            aVar.d("Alg.Alias.Signature.SHA1WITHECDSA", "ECDSA");
            aVar.d("Alg.Alias.Signature.ECDSAWITHSHA1", "ECDSA");
            aVar.d("Alg.Alias.Signature.SHA1WithECDSA", "ECDSA");
            aVar.d("Alg.Alias.Signature.ECDSAWithSHA1", "ECDSA");
            aVar.d("Alg.Alias.Signature.1.2.840.10045.4.1", "ECDSA");
            aVar.d("Alg.Alias.Signature." + ((Object) InterfaceC3890b.f33244j), "ECDSA");
            aVar.b("Signature.ECDDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA", g.f11437b);
            aVar.b("Signature.SHA1WITHECDDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA", g.f11437b);
            aVar.b("Signature.SHA224WITHECDDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA224", g.f11437b);
            aVar.b("Signature.SHA256WITHECDDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA256", g.f11437b);
            aVar.b("Signature.SHA384WITHECDDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA384", g.f11437b);
            aVar.b("Signature.SHA512WITHECDDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA512", g.f11437b);
            aVar.b("Signature.SHA3-224WITHECDDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSASha3_224", g.f11437b);
            aVar.b("Signature.SHA3-256WITHECDDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSASha3_256", g.f11437b);
            aVar.b("Signature.SHA3-384WITHECDDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSASha3_384", g.f11437b);
            aVar.b("Signature.SHA3-512WITHECDDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSASha3_512", g.f11437b);
            aVar.d("Alg.Alias.Signature.DETECDSA", "ECDDSA");
            aVar.d("Alg.Alias.Signature.SHA1WITHDETECDSA", "SHA1WITHECDDSA");
            aVar.d("Alg.Alias.Signature.SHA224WITHDETECDSA", "SHA224WITHECDDSA");
            aVar.d("Alg.Alias.Signature.SHA256WITHDETECDSA", "SHA256WITHECDDSA");
            aVar.d("Alg.Alias.Signature.SHA384WITHDETECDSA", "SHA384WITHECDDSA");
            aVar.d("Alg.Alias.Signature.SHA512WITHDETECDSA", "SHA512WITHECDDSA");
            h(aVar, "SHA224", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSA224", ki.r.f95309K5, g.f11437b);
            h(aVar, "SHA256", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSA256", ki.r.f95311L5, g.f11437b);
            h(aVar, "SHA384", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSA384", ki.r.f95313M5, g.f11437b);
            h(aVar, "SHA512", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSA512", ki.r.f95315N5, g.f11437b);
            h(aVar, "SHA3-224", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSASha3_224", Sh.d.f23350i0, g.f11437b);
            h(aVar, "SHA3-256", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSASha3_256", Sh.d.f23352j0, g.f11437b);
            h(aVar, "SHA3-384", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSASha3_384", Sh.d.f23354k0, g.f11437b);
            h(aVar, "SHA3-512", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSASha3_512", Sh.d.f23356l0, g.f11437b);
            h(aVar, "SHAKE128", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSAShake128", InterfaceC14453b.f98270q, g.f11437b);
            h(aVar, "SHAKE256", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSAShake256", InterfaceC14453b.f98271r, g.f11437b);
            h(aVar, "RIPEMD160", "ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSARipeMD160", InterfaceC3890b.f33245k, g.f11437b);
            aVar.b("Signature.SHA1WITHECNR", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecNR", g.f11437b);
            aVar.b("Signature.SHA224WITHECNR", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecNR224", g.f11437b);
            aVar.b("Signature.SHA256WITHECNR", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecNR256", g.f11437b);
            aVar.b("Signature.SHA384WITHECNR", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecNR384", g.f11437b);
            aVar.b("Signature.SHA512WITHECNR", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecNR512", g.f11437b);
            h(aVar, "SHA1", "CVC-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA", InterfaceC15005a.f104002s, g.f11437b);
            h(aVar, "SHA224", "CVC-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA224", InterfaceC15005a.f104003t, g.f11437b);
            h(aVar, "SHA256", "CVC-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA256", InterfaceC15005a.f104004u, g.f11437b);
            h(aVar, "SHA384", "CVC-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA384", InterfaceC15005a.f104005v, g.f11437b);
            h(aVar, "SHA512", "CVC-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA512", InterfaceC15005a.f104006w, g.f11437b);
            h(aVar, "SHA1", "PLAIN-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA", InterfaceC14273a.f97127d, g.f11437b);
            h(aVar, "SHA224", "PLAIN-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA224", InterfaceC14273a.f97128e, g.f11437b);
            h(aVar, "SHA256", "PLAIN-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA256", InterfaceC14273a.f97129f, g.f11437b);
            h(aVar, "SHA384", "PLAIN-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA384", InterfaceC14273a.f97130g, g.f11437b);
            h(aVar, "SHA512", "PLAIN-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA512", InterfaceC14273a.f97131h, g.f11437b);
            h(aVar, "RIPEMD160", "PLAIN-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecPlainDSARP160", InterfaceC14273a.f97132i, g.f11437b);
            h(aVar, "SHA3-224", "PLAIN-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA3_224", InterfaceC14273a.f97133j, g.f11437b);
            h(aVar, "SHA3-256", "PLAIN-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA3_256", InterfaceC14273a.f97134k, g.f11437b);
            h(aVar, "SHA3-384", "PLAIN-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA3_384", InterfaceC14273a.f97135l, g.f11437b);
            h(aVar, "SHA3-512", "PLAIN-ECDSA", "org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA3_512", InterfaceC14273a.f97136m, g.f11437b);
        }
    }

    static {
        HashMap hashMap = new HashMap();
        f11437b = hashMap;
        hashMap.put("SupportedKeyClasses", "java.security.interfaces.ECPublicKey|java.security.interfaces.ECPrivateKey");
        hashMap.put("SupportedKeyFormats", "PKCS#8|X.509");
    }
}
